### ISSUE TITLE
BERT models used for multi-lingual NER

### ISSUE THREAD

**Issue by stefan-it** [juntaoy/biaffine-ner#3]
Hi @juntaoy ,

thanks for releasing the code of your great paper :heart: 

I've one question regarding to the multi-lingual NER datasets (German, Spanish, Dutch): what BERT model do you use for training? Was it the BERT multi-lingual model or did you choose mono-lingual BERT models 🤔 Did you use cased or uncased version of a BERT model?

Many thanks in advance,

Stefan

**Comment by juntaoy** [comment]
Hi Stefan,

Thanks for your kind word:)
I used the multi-lingual one from original BERT repository:
multi_cased_L-12_H-768_A-12
https://storage.googleapis.com/bert_models/2018_11_23/multi_cased_L-12_H-768_A-12.zip
Best,

Juntao

**Comment by stefan-it** [comment]
Hi Juntao,

thanks for the explanation 🤗
