### ISSUE TITLE
the version of tf for extract_bert_feature

### ISSUE THREAD

**Issue by Sunnydx98** [juntaoy/biaffine-ner#32]
When i try to run extract_features.py, many errors occur, all of them such as :AttributeError: module 'tensorflow' has no attribute 'contrib', which is on account of the version of tf. Someone said in blog that Bert should be run in tf1.0 ,while the requirement.txt said we need tf2.0. Please give me some advice!!!!thk u!!!!

**Comment by juntaoy** [comment]
I see you took Amir's version that uses tf2.0. I think he didn't change the extract_features.py as that might be too complicated. The version I used for extract_features.py is tf1.12.

**Comment by Sunnydx98** [comment]
> I see you took Amir's version that uses tf2.0. I think he didn't change the extract_features.py as that might be too complicated. The version I used for extract_features.py is tf1.12.

thank u
