### ISSUE TITLE
请问方便给下ace2004和ace2005的数据预处理代码吗？

### ISSUE THREAD

**Issue by SCAUapc** [juntaoy/biaffine-ner#36]
您好！我尝试在generia数据集上使用您代码，确实效果很不错。关于ace数据集，根据《Joint mention extrac-
tion and classiﬁcation with mention hypergraphs》中写到，他们会删除一些overlap的entity，还有我看headline的text是不会被标注的，感觉这些部分还不少细节需要注意，所以您看预处理的代码能方便告知下吗？
十分感谢！

**Comment by cai-yuxiang** [comment]
你好，你已经解决了问题嘛，我也在预处理上出现问题了，十分感谢！！
