### ISSUE TITLE
关于论文里公式和代码实现的疑问

### ISSUE THREAD

**Issue by catnlp** [juntaoy/biaffine-ner#5]
**作者你好，我在看论文和代码的时候有个问题。在代码里只看到公式里第一项的实现（Um，也就是代码里的bilinear_map），但是没看到第二项（Wm）。是我看漏了还是代码还不完整？**
![公式](https://user-images.githubusercontent.com/37927693/84168852-7dcd7300-aaaa-11ea-950e-e5e709c6ecf4.PNG)
![实现](https://user-images.githubusercontent.com/37927693/84168861-80c86380-aaaa-11ea-9bb9-d8d3b096bc00.PNG)

**Comment by juntaoy** [comment]
你好，第二项Wm 被以下代码加到 Um 里提高运算效率了：
    if add_bias_1:
      vector_set_1 = tf.concat(
          [vector_set_1, tf.ones([batch_size, bucket_size, 1])], axis=2)
    if add_bias_2:
      vector_set_2 = tf.concat(
          [vector_set_2, tf.ones([batch_size, bucket_size, 1])], axis=2)
让我们假设batch_size 和 C=1 这样解释起来比较简单：
我们输入两个 n*d 的矩阵， 当你用上面的代码加如bias 以后矩阵变成了 n*(d+1)
这时候你需要建一个 （d+1）* 1 * （d+1）的 bilinear_map, 相比较原输入矩阵 你需要建的是一个 d*1*d 的bilinear_map 那么多出来的最后一行和最后一列就成了我们的Wm

**Comment by juntaoy** [comment]
In case anyone doesn't read Chinese:) Where is the corresponding code for the second term (Wm) in the equation.

So the Wm has been concatenated with Um to do fast inference, take a look at the code below:
if add_bias_1:
vector_set_1 = tf.concat(
[vector_set_1, tf.ones([batch_size, bucket_size, 1])], axis=2)
if add_bias_2:
vector_set_2 = tf.concat(
[vector_set_2, tf.ones([batch_size, bucket_size, 1])], axis=2)
Let's assume batch_size and number of label (C) equals 1 for easy explanation:
The inputs are two n x d matrix and when you add the bias using the code above the shape of the matrix becomes n x (d+1) as a result the bilinear_map becomes (d+1) x 1 x (d+1) in which the d x 1 x d (exclude the last row and last column) part is the Um and the last row and last column is the Wm in the equtions.

**Comment by catnlp** [comment]
> 你好，第二项Wm 被以下代码加到 Um 里提高运算效率了：
> if add_bias_1:
> vector_set_1 = tf.concat(
> [vector_set_1, tf.ones([batch_size, bucket_size, 1])], axis=2)
> if add_bias_2:
> vector_set_2 = tf.concat(
> [vector_set_2, tf.ones([batch_size, bucket_size, 1])], axis=2)
> 让我们假设batch_size 和 C=1 这样解释起来比较简单：
> 我们输入两个 n x d 的矩阵， 当你用上面的代码加如bias 以后矩阵变成了 n x (d+1)
> 这时候你需要建一个 （d+1）x 1 x （d+1）的 bilinear_map, 相比较原输入矩阵 你需要建的是一个 d x 1 x d 的bilinear_map 那么多出来的最后一行和最后一列就成了我们的Wm

哦哦，明白了，多谢
